/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#00677f",
        "tertiary": "#ffd690",
        "on-primary-fixed-variant": "#004e60",
        "primary-fixed": "#b7eaff",
        "surface-container-highest": "#353534",
        "on-tertiary-fixed": "#271900",
        "primary-container": "#00d1ff",
        "secondary-container": "#27ff97",
        "secondary": "#f5fff3",
        "inverse-surface": "#e5e2e1",
        "surface-bright": "#393939",
        "on-error": "#690005",
        "surface": "#131313",
        "on-primary-container": "#00566a",
        "on-tertiary-container": "#684900",
        "surface-variant": "#353534",
        "on-secondary-fixed": "#00210e",
        "on-tertiary": "#412d00",
        "tertiary-fixed": "#ffdea8",
        "surface-container-lowest": "#0e0e0e",
        "surface-container": "#201f1f",
        "secondary-fixed-dim": "#00e383",
        "on-error-container": "#ffdad6",
        "on-primary": "#003543",
        "outline-variant": "#3c494e",
        "tertiary-fixed-dim": "#ffba20",
        "on-tertiary-fixed-variant": "#5e4200",
        "secondary-fixed": "#5bffa1",
        "on-secondary-fixed-variant": "#00522c",
        "on-secondary-container": "#00723f",
        "error-container": "#93000a",
        "tertiary-container": "#f9b400",
        "on-primary-fixed": "#001f28",
        "surface-tint": "#4cd6ff",
        "error": "#ffb4ab",
        "background": "#131313",
        "on-secondary": "#00391d",
        "on-surface": "#e5e2e1",
        "primary-fixed-dim": "#4cd6ff",
        "inverse-on-surface": "#313030",
        "primary": "#a4e6ff",
        "surface-dim": "#131313",
        "on-background": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "surface-container-low": "#1c1b1b",
        "outline": "#859399",
        "on-surface-variant": "#bbc9cf"
      },
      fontFamily: {
        "headline": ["Lexend", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
